### ISSUE TITLE
Error generating dates in license file in windows

### ISSUE THREAD

**Issue by BrunoCoutinho** [open-license-manager/open-license-manager#10]
Line 207 of open-license-manager/src/tools/license-generator/license-generator.cpp is:
        oss << year << "-" << setfill('0') << std::setw(2) << month << "-" << day;

should be:
    oss << year << "-" << setfill('0') << std::setw(2) << month << "-" << std::setw(2) << day;

so day can have 2 digits in windows.

**Comment by gcontini** [comment]
Fixed in milestone 1.0.0
