### ISSUE TITLE
MINGW64 compile issue

### ISSUE THREAD

**Issue by cabbageqbj** [open-license-manager/open-license-manager#101]
Under MINGW64 ，I cmake the project
cmake .. -G "Visual Studio 16 2019" -A x64 -DBOOST_ROOT="C:\local\boost"
and it shows
-- Could NOT find **PkgConfig** (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find **lccgen** (missing: lccgen_DIR)
-- Submodule update
-- **Openssl** not found - generator - configuring libary without it.
-- architecture detected: x86_64
-- Found Boost: C:/local/boost_1_71_0 (found version "1.71.0") found components: date_time filesystem program_options system unit_test_framework
-- CXX compiler              : C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- CXX compiler flags        : /DWIN32 /D_WINDOWS /W3 /GR /EHsc
-- CXX compiler flags debug  : /MDd /Zi /Ob0 /Od /RTC1
-- CXX compiler flags release: /MD /O2 /Ob2 /DNDEBUG
-- Install prefix            : C:/Program Files (x86)/licensecc
-- External libs             : bcryptcrypt32ws2_32iphlpapi
-- Openssl not found, configuring the library without it (running in wine not supported).
-- architecture detected: x86_64
-- CXX compiler        : C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- CXX compiler flags  : /DWIN32 /D_WINDOWS /W3 /GR /EHsc
-- CXX compiler flags debug : /MDd /Zi /Ob0 /Od /RTC1
-- CXX compiler flags release: /MD /O2 /Ob2 /DNDEBUG
-- Install prefix      : C:/Program Files (x86)/licensecc
-- Project name        : DEFAULT
-- Project base dir    : C:/Users/77294/open-license-manager/projects/DEFAULT
-- Found Boost: C:/local/boost_1_71_0 (found version "1.71.0") found components: unit_test_framework system filesystem
-- Could NOT find **Doxygen** (missing: DOXYGEN_EXECUTABLE dot)
-- Could NOT find **Sphinx** (missing: SPHINX_EXECUTABLE)
-- Doxygen or Sphynx not found, not generating docs.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/77294/open-license-manager/build

It seems I need to install Doxygen Sphynx Openssl 
And need to set  PKG_CONFIG_EXECUTABLE  lccgen_DIR
I don't know how to install them .
Any help document can I find to config the compile environment ?

**Comment by gcontini** [comment]
For this kind of questions please use the user forum, so the answer will be useful to other users: [https://groups.google.com/g/licensecc](https://groups.google.com/g/licensecc)
It doesn't look like you're compiling for mingw... the logs are for visual studio. Please follow the [guide for compiling](http://open-license-manager.github.io/open-license-manager/development/Build-the-library-windows.html). 
The warning you're noticing are about optional packages. You should be able to compile after that. What's the error?
