### ISSUE TITLE
How to validate the license with client machines

### ISSUE THREAD

**Issue by zainul1114** [open-license-manager/open-license-manager#102]
Hi Team,
I am new to open-license-manager, currently i have setup open-license-manager software in on VM1 (openlm-master) and one more VM2 (openlm-client).  
My Environment : Both VMs are CentOS Linux release 7.7.1908
In VM1 i have installed open-license-manager by following link
https://github.com/open-license-manager/open-license-manager

```
[root@openlm-master open-license-manager]# ls projects/DEFAULT/include/licensecc/DEFAULT/
licensecc_properties.h  public_key.h
[root@openlm-master open-license-manager]# /root/openLM/open-license-manager/install/bin/lccgen license issue --valid-from 20200804 --valid-to 20200903 -s 08:00:27:57:de:bd -p /root/openLM/open-license-manager/projects/DEFAULT -o /root/openLM/open-license-manager/projects/DEFAULT/licenses/openlm-client.lic
License written
[root@openlm-master open-license-manager]#
[root@openlm-master licenses]# ls
openlm-client.lic
[root@openlm-master licenses]# less
Missing filename ("less --help" for help)
[root@openlm-master licenses]# cat  openlm-client.lic
[DEFAULT]
lic_ver = 200
client-signature = 08:00:27:57:de:bd
valid-from = 2020-08-04
valid-to = 2020-09-03
sig = I2pyXxvib0V2/AWPxzgrl+XiZRZbBd80SNbPC+EUS9sj39+5GziW65jjdDqFtUUSGmJiGtpcwzmHYwtyThfzoD/+kq2ZtS/lsoevd4uwLge4Ws5sFILPMLwjVF8Z83RtBeWsnjGDqG16lMBTqVcZCZrjHz3KSbG1mpWHfhM++q0=

[root@openlm-master licenses]#
Note: Here i took VM2 MAC Address to generate license with --valid-from and --valid-to
[root@openlm-master open-license-manager]# tree projects/
projects/
└── DEFAULT
    ├── include
    │   └── licensecc
    │       └── DEFAULT
    │           ├── licensecc_properties.h
    │           └── public_key.h
    ├── licenses
    │   └── openlm-client.lic
    └── private_key.rsa

5 directories, 4 files
[root@openlm-master open-license-manager]#

```
Is that correct way to generate license file from VM1? 
Here i want to create and generate/renew the license for VM2 using open-license-manager from VM1.
Please guide me what are the steps do i need to follow on VM1 and VM2 now.

Regards,
Zain

**Comment by gcontini** [comment]
Hi Zain,
Sorry for the very late reply. The procedure is explained here: [issue licenses](http://open-license-manager.github.io/open-license-manager/usage/issue-licenses.html)

unfortunately `lcc` can't generate licenses directly using the mac address. you need to run an executable in the client machine (vm2). 

Your way to use it is nice. I've opened [an issue](https://github.com/open-license-manager/lcc-license-generator/issues/12) for it.
