### ISSUE TITLE
Widnows - identify_pc picks up a virtual adapter (vpn) with no mac address

### ISSUE THREAD

**Issue by p1m3nt** [open-license-manager/open-license-manager#107]
When I was using the lccinspector.exe to generate hardware identifiers, it printed out:
`DEFAULT:AAAA-AAAA-AAA=`
`MAC:AAAA-AAAA-AAA=`
`IP:ACAA-AAAq-Kio=`
`Disk1:AFvw-8XwA-AAA=`
`Disk2:AG5U-RlMA-AAA=`
Clearly, the identifiers are not in the format of XXXX-XXXX-XXXX-XXXX as described in the document. And they can be used with lccgen.exe to generate lic file without error, however it cannot be verified as a license linked to a specific machine, also as it's mentioned in the document. Any help here? Thanks. I build with cmake and vs 2017

**Comment by gcontini** [comment]
Hi,
the format of hardware identifiers has changed recently, so XXXX-XXXX-XXXX is now correct.

 - Can you add the full output of lccinspector? (seem one of the network cards isn't detected well, it may be as well related to #67, the code picking up some virtual adapter). 
 - please run `ipconfig /all` and attach the output
 - Can you try to use the examples project to verify the license, just to exclude any other source of error? https://github.com/open-license-manager/examples
 - what if you generate the license using the disk identifier? does it work?
    - if this is the case find the file "licensecc_properties.h" and change:

```
#define LCC_BARE_TO_METAL_STRATEGIES { STRATEGY_DISK_NUM, STRATEGY_NONE }
```
then see if the default strategy now reports the right identifier.

**Comment by p1m3nt** [comment]
Thanks very much, Gabriele.

- the full output from lccinspector:
`DEFAULT:AAAA-AAAA-AAA=`
`MAC:AAAA-AAAA-AAA=`
`IP:ACAA-AAAq-Kio=`
`Disk1:AFvw-8XwA-AAA=`
`Disk2:AG5U-RlMA-AAA=`
`Virtualiz. class :No virtualization`
`Virtualiz. detail:No virtualization`
`Cloud provider   :On premise hardware (no cloud)`
`Cpu Vendor       :GenuineIntel`
`Cpu Brand        :Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz`
`Cpu hypervisor   :0`
`Cpu model        :0x206e9`
`Bios vendor      :X405UA`
`Bios description :1.0       X`
`System vendor    :ASUSTEK COMPUTER INC.`
`==================`

- the full output from Windows IP Configuration:
`Windows IP Configuration`
`   Host Name . . . . . . . . . . . . : DESKTOP-03G0272`
`   Primary Dns Suffix  . . . . . . . :`
`   Node Type . . . . . . . . . . . . : Hybrid`
`   IP Routing Enabled. . . . . . . . : No`
`   WINS Proxy Enabled. . . . . . . . : No`
`   DNS Suffix Search List. . . . . . : lan`
`Unknown adapter Astrill VPN:`
`   Media State . . . . . . . . . . . : Media disconnected`
`   Connection-specific DNS Suffix  . :`
`   Description . . . . . . . . . . . : Wintun Userspace Tunnel`
`   Physical Address. . . . . . . . . :`
`   DHCP Enabled. . . . . . . . . . . : No`
`   Autoconfiguration Enabled . . . . : Yes`
`Ethernet adapter 以太网:`
`   Media State . . . . . . . . . . . : Media disconnected`
`   Connection-specific DNS Suffix  . :`
`   Description . . . . . . . . . . . : Realtek PCIe GBE Family Controller`
`   Physical Address. . . . . . . . . : 2C-FD-A1-40-09-54`
`   DHCP Enabled. . . . . . . . . . . : Yes`
`   Autoconfiguration Enabled . . . . : Yes`
`Wireless LAN adapter 本地连接* 1:`
`   Media State . . . . . . . . . . . : Media disconnected`
`   Connection-specific DNS Suffix  . :`
`   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter`
`   Physical Address. . . . . . . . . : 42-9F-38-D1-33-85`
`   DHCP Enabled. . . . . . . . . . . : Yes`
`   Autoconfiguration Enabled . . . . : Yes`
`Wireless LAN adapter 本地连接* 2:`
`   Media State . . . . . . . . . . . : Media disconnected`
`   Connection-specific DNS Suffix  . :`
`   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2`
`   Physical Address. . . . . . . . . : C2-9F-38-D1-33-85`
`   DHCP Enabled. . . . . . . . . . . : Yes`
`   Autoconfiguration Enabled . . . . : Yes`
`Wireless LAN adapter WLAN:`
`   Connection-specific DNS Suffix  . : lan`
`   Description . . . . . . . . . . . : Realtek 8822BE Wireless LAN 802.11ac PCI-E NIC`
`   Physical Address. . . . . . . . . : 40-9F-38-D1-33-85`
`   DHCP Enabled. . . . . . . . . . . : Yes`
`   Autoconfiguration Enabled . . . . : Yes`
`   Link-local IPv6 Address . . . . . : fe80::14df:664e:f2f6:4d4a%6(Preferred)`
`   IPv4 Address. . . . . . . . . . . : 192.168.100.106(Preferred)`
`   Subnet Mask . . . . . . . . . . . : 255.255.255.0`
`   Lease Obtained. . . . . . . . . . : Thursday, October 22, 2020 10:51:32 PM`
`   Lease Expires . . . . . . . . . . : Friday, October 23, 2020 10:51:44 PM`
`   Default Gateway . . . . . . . . . : 192.168.100.1`
`   DHCP Server . . . . . . . . . . . : 192.168.100.1`
`   DHCPv6 IAID . . . . . . . . . . . : 54566712`
`   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-23-CA-08-93-2C-FD-A1-40-09-54`
`   DNS Servers . . . . . . . . . . . : 192.168.100.1`
`   NetBIOS over Tcpip. . . . . . . . : Enabled`
`Ethernet adapter 蓝牙网络连接:`
`   Media State . . . . . . . . . . . : Media disconnected`
`   Connection-specific DNS Suffix  . :`
`   Description . . . . . . . . . . . : Bluetooth Device (Personal Area Network)`
`   Physical Address. . . . . . . . . : 40-9F-38-D1-33-84`
`   DHCP Enabled. . . . . . . . . . . : Yes`
`   Autoconfiguration Enabled . . . . : Yes`

Following your suggestions, when I use the disk identifier to generate license, it works. The output from licensed machine:
`license to sign [KEY_GENERATORclient-signatureAFvw-8XwA-AAA=lic_ver200]`
`EventReg[step:4,events:{[ev:101,sev:0ref:C:\Users\18473\source\repos\security_test\bin\x64\Debug\key_generator\key_generator.lic][ev:102,sev:0ref:C:\Users\18473\source\repos\security_test\bin\x64\Debug\key_generator\key_generator.lic][ev:103,sev:0ref:C:\Users\18473\source\repos\security_test\bin\x64\Debug\key_generator\key_generator.lic][ev:0,sev:0ref:C:\Users\18473\source\repos\security_test\bin\x64\Debug\key_generator\key_generator.lic]]`
`license OK`

The output from an unlicensed one:
`license to sign [KEY_GENERATORclient-signatureAFvw-8XwA-AAA=lic_ver200]`
`EventReg[step:3,events:{[ev:101,sev:0ref:C:\Users\wj\Desktop\key_generator\key_generator.lic][ev:102,sev:0ref:C:\Users\11255\Desktop\key_generator\key_generator.lic][ev:103,sev:0ref:C:\Users\11255\Desktop\key_generator\key_generator.lic][ev:9,sev:2ref:C:\Users\11255\Desktop\key_generator\key_generator.lic]]`
`license ERROR :`
`    Calculated identifier and the one provided in license didn't match`
`hardware id is :`
`   AEvr-yiYA-AAA=`

If I understand correctly, if there's any virtual adapter installed (like it's a vpn installed on my laptop), I'd better use disk or memory cpu or host name identifier? Can I combine strategies to generate license, with something like:
`#define LCC_BARE_TO_METAL_STRATEGIES { STRATEGY_DISK_NUM, STRATEGY_DISK_LABEL, STRATEGY_MEMORY_CPU_SIZE, STRATEGY_HOST_NAME, STRATEGY_NONE }`?

And when I distribute the licensed software to clients, only the lic file should be sent to them, i.e. I'm the only one who keeps all the private_key.rsa files as the public_key.h is compiled within the software?

Again thanks for help.

**Comment by gcontini** [comment]
Hi p1m3nt 
I agree, disk strategy is a bit more stable in Windows, i'll set it as default from next commits. 
On the other hand this is a bug that has been there for a long time, it's time to fix it. Let me review the code and find a workaround (also thanks very much for your informations I also have a vpn installed in my pc but it seems to work fine).

Answering your other questions:
 - You don't have to distribute any other thing except the license file and the licensed software.
    - The public key is compiled inside the library (DS) so it's distributed automatically. While the private key doesn't leave the computer used to generate licenses.

you can get the hardware identifier in your software trough the api: (see examples)
'''
bool identify_pc(LCC_API_HW_IDENTIFICATION_STRATEGY hw_id_method, char* identifier_out, size_t* buf_size,
				 ExecutionEnvironmentInfo* execution_environment_info);
'''
If you pass the parameter `DEFAULT_STRATEGY` it will try all the strategies you define in `LCC_BARE_TO_METAL_STRATEGIES` in sequence. So your proposed configuration is correct (teoretically). But for the moment only DISK and NETWORK (ip,ethernet) are working. If you want CPU you have to implement by yourself (or wait I find the time to do). It isn't difficult. The low level funcitons are there, the interfaces are very simple, and we're happy to accept contributions ;) .

Usually you don't need to send `lccinspector` to your clients except if they have problems.

If a client has an issue (eg.reports you an identifier like 'AAAA-AAAA-AAA=') you can ask him to set the environment variable 'IDENTIFICATION_STRATEGY' and try again. eg.
```
set IDENTIFICATION_STRATEGY=1 
```
will make DEFAULT_STRATEGY use 'STRATEGY_IP_ADDRESS'. See the workflow in: http://open-license-manager.github.io/open-license-manager/usage/Hardware-identifiers.html
(i've improved the docs with this notes i'm sending you, wait some day they'll be online)

**Comment by p1m3nt** [comment]
Hi Gabriele, thanks for the explanation. I'd like to contribute once I figure out how to implement it.

**Comment by p1m3nt** [comment]
A quick question, is it possible to license a dll instead of an exe which loads it? Thanks.

**Comment by gcontini** [comment]
I don't think there are any issues with this. If you have problems feel free to open another bug.

**Comment by gcontini** [comment]
Interfaces with mac address 0 are excluded, interfaces adapters with a non-zero mac address are then sorted by their name. if it contains vpn or ppp they go last.
