### ISSUE TITLE
it is not useful

### ISSUE THREAD

**Issue by sxdxwb** [open-license-manager/open-license-manager#13]
I test the software in two computers,which  named A and B.A computer's signature is IAAA-AAAA-LzgV-7AAA , B computer's signature is IAAA-AAAA-KudG-xQAA。when i copy A's ./example  and license to B, the B return  "licence OK".
I did some experiments in different computers,I found the different computers has common prefix “ IAAA-AAAA“,the postfix didn't inflent the result,all return OK.only prefix influnt the resule,but the prefix is same.
Is my way of using it wrong?

**Comment by GlLamant** [comment]
I have same problem, I fixed it by adding some codes to  compare the client_signature and a string which returns from  generate_user_pc_signature, i return LICENSE_OK if two strings is same.

**Comment by willamowius** [comment]
Pull request with fix submitted: #19
