### ISSUE TITLE
can't find public-key.h and build_properties.h

### ISSUE THREAD

**Issue by Dearge** [open-license-manager/open-license-manager#16]
pc-identifiers.h and build_properties.h are missing in the project, can they be put up? Otherwise, the procedure will always fail.

**Comment by huoweijing0326** [comment]
public-key.h and build_properties.h are put up by make.

**Comment by gcontini** [comment]
This issue is too old to be investigate @Dearge if you still have the problem please comment here. I'll try to help. The two files should be generated in the build process.
Specify environment/compiler...
