### ISSUE TITLE
Compile error in Centos7

### ISSUE THREAD

**Issue by vkkindia** [open-license-manager/open-license-manager#53]
After initial struggle i am compiling this program in centos 7, now halted at this error message:
Could proceed further, what library am i  missing ??
proceeded as suggested in your page.
---------------------

/usr/bin/c++   -pipe -fmessage-length=0 -std=c++11 -Wuninitialized -fPIC  -pthread -static-libstdc++ -rdynamic CMakeFiles/bootstrap.dir/bootstrap.cpp.o  -o bootstrap ../../../lib/libtools_base.a -lz -ldl 
../../../lib/libtools_base.a(CryptoHelperLinux.cpp.o): In function `license::CryptoHelperLinux::CryptoHelperLinux()':
CryptoHelperLinux.cpp:(.text+0xd5): undefined reference to `ERR_load_ERR_strings'
CryptoHelperLinux.cpp:(.text+0xda): undefined reference to `ERR_load_crypto_strings'
CryptoHelperLinux.cpp:(.text+0xdf): undefined reference to `OPENSSL_add_all_algorithms_noconf'
../../../lib/libtools_base.a(CryptoHelperLinux.cpp.o): In function `license::CryptoHelperLinux::generateKeyPair()':
CryptoHelperLinux.cpp:(.text+0x107): undefined reference to `RSA_generate_key'
../../../lib/libtools_base.a(CryptoHelperLinux.cpp.o): In function `license::CryptoHelperLinux::exportPrivateKey() const':
CryptoHelperLinux.cpp:(.text+0x1cc): undefined reference to `BIO_s_mem'
CryptoHelperLinux.cpp:(.text+0x1d4): undefined reference to `BIO_new'
CryptoHelperLinux.cpp:(.text+0x20d): undefined reference to `PEM_write_bio_RSAPrivateKey'
CryptoHelperLinux.cpp:(.text+0x228): undefined reference to `BIO_ctrl'
CryptoHelperLinux.cpp:(.text+0x25a): undefined reference to `BIO_read'
CryptoHelperLinux.cpp:(.text+0x409): undefined reference to `BIO_free_all'
../../../lib/libtools_base.a(CryptoHelperLinux.cpp.o): In function `license::CryptoHelperLinux::exportPublicKey() const':
CryptoHelperLinux.cpp:(.text+0x608): undefined reference to `BIO_s_mem'
CryptoHelperLinux.cpp:(.text+0x610): undefined reference to `BIO_new'
CryptoHelperLinux.cpp:(.text+0x62e): undefined reference to `PEM_write_bio_RSAPublicKey'
CryptoHelperLinux.cpp:(.text+0x649): undefined reference to `BIO_ctrl'
CryptoHelperLinux.cpp:(.text+0x67b): undefined reference to `BIO_read'
CryptoHelperLinux.cpp:(.text+0x82a): undefined reference to `BIO_free_all'
../../../lib/libtools_base.a(CryptoHelperLinux.cpp.o): In function `license::CryptoHelperLinux::signString(void const*, unsigned long, std::string const&) const':
CryptoHelperLinux.cpp:(.text+0x9ac): undefined reference to `EVP_MD_CTX_create'
CryptoHelperLinux.cpp:(.text+0xa44): undefined reference to `BIO_new_mem_buf'
CryptoHelperLinux.cpp:(.text+0xa63): undefined reference to `PEM_read_bio_PrivateKey'
CryptoHelperLinux.cpp:(.text+0xa73): undefined reference to `BIO_free'
CryptoHelperLinux.cpp:(.text+0xa78): undefined reference to `EVP_sha256'
CryptoHelperLinux.cpp:(.text+0xa98): undefined reference to `EVP_DigestSignInit'
CryptoHelperLinux.cpp:(.text+0xaae): undefined reference to `EVP_MD_CTX_destroy'
CryptoHelperLinux.cpp:(.text+0xae4): undefined reference to `EVP_DigestUpdate'
CryptoHelperLinux.cpp:(.text+0xafa): undefined reference to `EVP_MD_CTX_destroy'
CryptoHelperLinux.cpp:(.text+0xb85): undefined reference to `EVP_DigestSignFinal'
CryptoHelperLinux.cpp:(.text+0xb9b): undefined reference to `EVP_MD_CTX_destroy'
CryptoHelperLinux.cpp:(.text+0xc34): undefined reference to `CRYPTO_malloc'
CryptoHelperLinux.cpp:(.text+0xc50): undefined reference to `EVP_MD_CTX_destroy'
CryptoHelperLinux.cpp:(.text+0xcdd): undefined reference to `EVP_DigestSignFinal'
CryptoHelperLinux.cpp:(.text+0xcf7): undefined reference to `CRYPTO_free'
CryptoHelperLinux.cpp:(.text+0xd03): undefined reference to `EVP_MD_CTX_destroy'
CryptoHelperLinux.cpp:(.text+0xdaa): undefined reference to `EVP_PKEY_free'
CryptoHelperLinux.cpp:(.text+0xdbd): undefined reference to `CRYPTO_free'
CryptoHelperLinux.cpp:(.text+0xdd0): undefined reference to `EVP_MD_CTX_destroy'
../../../lib/libtools_base.a(CryptoHelperLinux.cpp.o): In function `license::CryptoHelperLinux::Opensslb64Encode(unsigned long, unsigned char*) const':
CryptoHelperLinux.cpp:(.text+0xf24): undefined reference to `BIO_s_mem'
CryptoHelperLinux.cpp:(.text+0xf2c): undefined reference to `BIO_new'
CryptoHelperLinux.cpp:(.text+0xf35): undefined reference to `BIO_f_base64'
CryptoHelperLinux.cpp:(.text+0xf3d): undefined reference to `BIO_new'
CryptoHelperLinux.cpp:(.text+0xf54): undefined reference to `BIO_push'
CryptoHelperLinux.cpp:(.text+0xf69): undefined reference to `BIO_set_flags'
CryptoHelperLinux.cpp:(.text+0xf82): undefined reference to `BIO_write'
CryptoHelperLinux.cpp:(.text+0xf9d): undefined reference to `BIO_ctrl'
CryptoHelperLinux.cpp:(.text+0xfba): undefined reference to `BIO_ctrl'
CryptoHelperLinux.cpp:(.text+0xfee): undefined reference to `BIO_free_all'
../../../lib/libtools_base.a(CryptoHelperLinux.cpp.o): In function `license::CryptoHelperLinux::~CryptoHelperLinux()':
CryptoHelperLinux.cpp:(.text+0x1044): undefined reference to `RSA_free'
collect2: error: ld returned 1 exit status
make[2]: *** [src/tools/bootstrap/bootstrap] Error 1

**Comment by gcontini** [comment]
Have you had a look to .travis.yml file? there is a section for compiling in centos 7 (we're compiling it in a docker, however the procedure should be the same as standard vm).
see if your procedure matches the procedure in there.
Seem openssl is missing...

**Comment by vkkindia** [comment]
Thanks, finally i managed to compile successfully.
Openssl was not missing , some issues with cmake. When tried with cmake-gui
it was successful.
Might be useful for someone.

**Comment by gcontini** [comment]
Updated docs with reference to this bug and new compilation instructions.
