### ISSUE TITLE
Crash when I push a wrong license

### ISSUE THREAD

**Issue by z-pc** [open-license-manager/open-license-manager#54]
I'm running a ./example
I deliberately provided for example.exe a wrong license (specifically: I get your ID in introduce: Jaaa-aaaa-MG9F-ZhB to license_generator gen example.lic, then check this lic by example.exe) to handle a behaviors.
But It crash at 
```
EVENT_TYPE result = acquire_license("example", licenseLocation, &licenseInfo);
```
Deeper, I creating debugger dump: 
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\vcruntime\thread_safe_statics.cpp --> static int __cdecl __scrt_initialize_thread_safe_statics() throw() --> auto const wake_all_condition_variable   = GET_PROC_ADDRESS(kernel32, WakeAllConditionVariable);

How can I do?

**Comment by z-pc** [comment]
Sorry.
I used boots1670 in environment path, It seems this is causing an error.
I try boots170 x64. 
It worked

**Comment by gcontini** [comment]
Boost 1.67 _should_ be supported. And Boost is used only by the `license_generator` and the tests, it shouldn't affect `example.exe` (see the CmakeLists.txt in `example` folder)

By the way, I am trying to reproduce it but i don't understand. What you were doing exactly? 
1) generate a license with license_generator (here you shouldn't be able to use the malformed license id, there is a regexp to prevent it)
2) manually modify the license
3) run the example with the malformed license
is that so?
