### ISSUE TITLE
How to include this in my c program

### ISSUE THREAD

**Issue by vkkindia** [open-license-manager/open-license-manager#55]
How to include this in my c program.
Any example.

**Comment by gcontini** [comment]
see the section "how to use" in the readme file
there is a folder named "example" with a basic application. you can start from there.
If you see the QA section in the wiki this project is still in alpha stage, some effort (read the code understand how it works) is required. If you want to contribute with documentation you're welcome :smile:

**Comment by gcontini** [comment]
closing it, if not clear please reopen and comment.
