### ISSUE TITLE
provide a better computer identifier

### ISSUE THREAD

**Issue by open-license-manager** [open-license-manager/open-license-manager#6]
The computer identifier should be 12 bytes long (to be coded as 16 Base36 ascii chars)
It should include:
1) physical memory
2) cpu type
3) license number(windows)/dbus guid (Linux)
4) computer name(windows)/hostname (linux)
5) 1 or more mac address of connected network cards
6) 1 or more disk identifier

**Comment by gcontini** [comment]
implemented https://github.com/open-license-manager/open-license-manager/wiki/hardware-identifiers to take care of different environment and cases
