### ISSUE TITLE
What is the mean of "source" and "licenseVersion" of the FullLicenseInfo ?

### ISSUE THREAD

**Issue by z-pc** [open-license-manager/open-license-manager#62]
What is the mean of "source" and "licenseVersion" of the FullLicenseInfo ?
Sorry, because I don't find anywhere use them.

**Comment by gcontini** [comment]
`FullLicenseInfo` is an internal structure that will be abandoned soon.
`source` is the file name where the license is stored. licenseVersion is the version of the licensing software (1.1.0)
If you're starting exploring the library i suggest you to start from the public api under `api/license++.h`
