### ISSUE TITLE
build error no such file public-key.h

### ISSUE THREAD

**Issue by HammerZhao** [open-license-manager/open-license-manager#66]
[ 23%] Building C object src/library/os/CMakeFiles/os.dir/os.c.o
cd /root/open-license-manager-1.1.0/build/src/library/os && /usr/bin/cc  -DBOOST_ALL_NO_LIB -DBOOST_LIB_DIAGNOSTIC -pipe -fmessage-length=0 -Wall -Wuninitialized -fPIC -I/root/open-license-manager-1.1.0/build    -o CMakeFiles/os.dir/os.c.o   -c /root/open-license-manager-1.1.0/src/library/os/os.c
/root/open-license-manager-1.1.0/src/library/os/os.c:3:24: fatal error: public-key.h: No such file or directory

**Comment by gcontini** [comment]
The public key file should be generated during the build process. Are you following the build instructions for your environment?

https://github.com/open-license-manager/open-license-manager/wiki/Build-the-library

Please follow the contributing guidelines for reporting a bug:

https://github.com/open-license-manager/open-license-manager/blob/develop/CONTRIBUTING.md

Include the environment and the exact steps to reproduce your bug. as the version you downloaded... As you can see the library compiles in 8 different environments,

https://travis-ci.org/open-license-manager/open-license-manager

Did you try the develop branch? should be stable enough.

**Comment by gcontini** [comment]
no further evidence, closing it
