### ISSUE TITLE
Lcc submodule not found: _Could NOT find lcc (missing: lcc_DIR)

### ISSUE THREAD

**Issue by CasonTsai** [open-license-manager/open-license-manager#71]
i compiler this project in win10,but i get this error  follow below 

_Could NOT find lcc (missing: lcc_DIR)
CMake Error at cmake/Findlcc.cmake:80 (add_subdirectory):
  The source directory

 E:/thirdParty_lib/encryption/open-license-manager-develop/extern/license-generator

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:30 (find_package)

Found openssl version 1.0.2p
architecture detected: x86_64
C compiler        : D:/Code-software/vs2019/install/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
C compiler flags  : /DWIN32 /D_WINDOWS /W3
CXX compiler      : D:/Code-software/vs2019/install/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
CXX compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
CXX compiler flags debug : /MDd /Zi /Ob0 /Od /RTC1
CXX compiler flags release: /MD /O2 /Ob2 /DNDEBUG
Install prefix    : C:/Program Files (x86)/licensecc
Project name      : DEFAULT
Project base dir  : E:/thirdParty_lib/encryption/open-license-manager-develop/projects/DEFAULT
Found Boost: E:/thirdParty_lib/boost/boost_1_69_0 (found version "1.69.0") found components: unit_test_framework system filesystem 
Configuring incomplete, errors occurred!
See also "E:/thirdParty_lib/encryption/open-license-manager-develop/build/CMakeFiles/CMakeOutput.log"._

my env is :
system: windows10
cmake version : cmake 3.16.2
msvc version : msvc 14

**Comment by gcontini** [comment]
did you `git clone`  with the `--recursive` option? 

-- documentation updated. See wiki about compiling under windows

**Comment by CasonTsai** [comment]
@gcontini  my fault,i forgot add --recursive,i download it from web browser, i have finished it ,thx
