### ISSUE TITLE
base64 not recognized value error

### ISSUE THREAD

**Issue by tankienleong** [open-license-manager/open-license-manager#78]
Hi, I am using ubuntu 16.04.

I am following the tutorial from this link to generate license 
https://github.com/open-license-manager/examples/tree/develop/submodule

I get the error "base64 not recognized value error" after I run 

$ bin/lcc license issue -p ../projects/DEFAULT/ -o example.lic

Besides that, it also shows "License writing error: Private key file [/home/ubuntu/open-license-manager/examples/submodule/build/private_key.rsa] does not exists"

Do I need to generate the private key file manually and put in /home/ubuntu/open-license-manager/examples/submodule/build/ directory?

**Comment by gcontini** [comment]
Thank you in advance for reporting.
The example project was outdated, and there was a bug in `lccgen`. 
Please give it a second try now, if still don't work reopen the bug and comment.
