### ISSUE TITLE
Windows build failed on license_generator

### ISSUE THREAD

**Issue by senthilsam** [open-license-manager/open-license-manager#87]
![image](https://user-images.githubusercontent.com/4089212/80569976-9ceed480-8a17-11ea-9b56-b1a655ad4f28.png)
 I am getting this error during compile. Please assist me to fix this

**Comment by senthilsam** [comment]
I have fixed this by adding static_cast<std::string>. Is this correct

**Comment by gcontini** [comment]
Hi Senthilsam,
i don't see this issue: the project is compiling fine under VS 2017~2019 . The documentation is incorrectly reporting compatibility with VS 2015 (I'm fixing this now). Are you using visual studio 2015 by chance?

**Comment by senthilsam** [comment]
Yes i am using vs 2015

**Comment by gcontini** [comment]
Sorry but the compatibility with VisualStudio 2015 was in version 1.x of the software. If Visual Stuido 2015 is a must for your project you can download the branch [fix-v1.0.0](https://github.com/open-license-manager/open-license-manager/tree/fix-v1.0.0) though it's very old and unsupported.
Version 2 only supports Visual studio 2017 and beyond.
