### ISSUE TITLE
Build fails : commit hash 6a80dbc2c74e3af8eff532e8be399122eeee5d14

### ISSUE THREAD

**Issue by nyue** [open-license-manager/open-license-manager#91]
[ 25%] Building CXX object src/library/hw_identifier/CMakeFiles/hw_identifier.dir/hw_identifier_facade.cpp.o
In file included from /home/nyue/projects/Open-License-Manager/OLM/Open-License-Manager_git/src/library/hw_identifier/hw_identifier_facade.hpp:14:0,
                 from /home/nyue/projects/Open-License-Manager/OLM/Open-License-Manager_git/src/library/hw_identifier/hw_identifier_facade.cpp:8:
/home/nyue/projects/Open-License-Manager/OLM/Open-License-Manager_git/include/licensecc/datatypes.h:109:20: error: ‘LCC_API_FEATURE_NAME_SIZE’ was not declared in this scope
  char feature_name[LCC_API_FEATURE_NAME_SIZE +
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/nyue/projects/Open-License-Manager/OLM/Open-License-Manager_git/include/licensecc/datatypes.h:109:20: note: suggested alternative: ‘LCC_API_PROJECT_NAME_SIZE’
  char feature_name[LCC_API_FEATURE_NAME_SIZE +
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
                    LCC_API_PROJECT_NAME_SIZE
src/library/hw_identifier/CMakeFiles/hw_identifier.dir/build.make:62: recipe for target 'src/library/hw_identifier/CMakeFiles/hw_identifier.dir/hw_identifier_facade.cpp.o' failed
make[2]: *** [src/library/hw_identifier/CMakeFiles/hw_identifier.dir/hw_identifier_facade.cpp.o] Error 1
CMakeFiles/Makefile2:1535: recipe for target 'src/library/hw_identifier/CMakeFiles/hw_identifier.dir/all' failed
make[1]: *** [src/library/hw_identifier/CMakeFiles/hw_identifier.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gcontini** [comment]
There was an incompatible change in the api parameter names. Sorry for that.

You should find the file `licensecc_properties.h` in your project and delete it if you haven't customized it or rename `LCC_API_PROJECT_NAME_SIZE` into `LCC_API_FEATURE_NAME_SIZE` if the file was customized.

The file is not committed to git because it's subject to your customizations and should be automatically generated if not found.

**Comment by gcontini** [comment]
I've added some instructions on the user forums https://groups.google.com/forum/#!topic/licensecc/UJR3vbihOQc

later i'll modify the docs too. Let's close this for now, if you still have the issue please reopen it.
