### ISSUE TITLE
Fail to cmake on linux 

### ISSUE THREAD

**Issue by cabbageqbj** [open-license-manager/open-license-manager#99]
The error log is 
/opt/tools/gcc/bin/c++  DCHECK_FUCTION_EXISTS=pthread_create
...
cannot find -lpthreads

Centos 7.7.7908 

It seems that I should use -pthread instead of -lpthreads?
I have no idea why and how to complie it ?
Hope some idea

**Comment by gcontini** [comment]
Are you following the compilation instructions here?
http://open-license-manager.github.io/open-license-manager/development/Build-the-library.html
If so and you still have errors  you can check inside the `.travis.yml` file, there is a section centos 7 (well it's compiling in a centos 7 docker, but it should be the same...)

**Comment by gcontini** [comment]
inactive for long time tentatively closing it.
